backend:
  name: git-gateway
  branch: main

site_url: "https://calincake.netlify.app"

media_folder: "images/uploads"
public_folder: "/images/uploads"

# Une première collection simple pour valider que tout marche
collections:
  - name: "settings"
    label: "Paramètres du site"
    editor:
      preview: false
    files:
      - file: "data/settings.json"
        label: "Réglages généraux"
        name: "general"
        fields:
          - { label: "Email contact", name: "contact_email", widget: "string", default: "contact@calincake.com" }
          - { label: "Instagram", name: "instagram", widget: "string", default: "@calincake" }
