backend:
  name: git-gateway
  branch: main   # ou master si ton dépôt utilise "master"

media_folder: "images"      # là où sont/seront tes images dans le repo
public_folder: "/images"

publish_mode: simple

# Une petite collection "Contenu" pour éditer quelques textes clés,
# (tu pourras agrandir ensuite)
collections:
  - name: "accueil"
    label: "Accueil"
    files:
      - label: "Section Hero"
        name: "hero"
        file: "index.html"
        editor:
          preview: false
        fields:
          - { label: "Titre (H1)", name: "h1", widget: "string", hint: "Le gros titre" }
          - { label: "Lead", name: "lead", widget: "text", hint: "Paragraphe sous le titre" }

# Astuce images : va dans l’onglet Media de l’admin pour téléverser
# et remplacer les fichiers /images/... (en gardant les mêmes noms).
